services:
	server:
		build: .
		restart: always
		ports:
			- 8080:8080
		depends_on:
			- mysqldb
	mysqldb:
		image: mysql
		restart: always
		environment:
			MYSQL_DATABASE: TodolistDB
			MYSQL_USER: sengwah123
			MYSQL_PASSWORD: sengwah123
			MYSQL_ROOT_PASSWORD: sengwah123